/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'author' : UserId,
  'timestamp' : Time,
  'postId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'recipient' : UserId,
  'sender' : UserId,
  'timestamp' : Time,
}
export interface Notification {
  'id' : Time,
  'user' : UserId,
  'message' : string,
  'timestamp' : Time,
}
export interface Post {
  'id' : bigint,
  'content' : string,
  'imageBlob' : [] | [ExternalBlob],
  'author' : UserId,
  'timestamp' : Time,
  'category' : [] | [string],
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'avatarBlob' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDiscussionPost' : ActorMethod<[string, string, string], bigint>,
  'createPost' : ActorMethod<[string, [] | [ExternalBlob]], bigint>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllUsers' : ActorMethod<[], Array<[UserId, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getFeed' : ActorMethod<[], Array<Post>>,
  'getFollowedFeed' : ActorMethod<[], Array<Post>>,
  'getFollowers' : ActorMethod<[UserId], Array<UserId>>,
  'getLikes' : ActorMethod<[bigint], bigint>,
  'getMessages' : ActorMethod<[UserId], Array<Message>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPost' : ActorMethod<[bigint], Post>,
  'getPostsByCategory' : ActorMethod<[string], Array<Post>>,
  'getProfile' : ActorMethod<[UserId], UserProfile>,
  'getUserFeed' : ActorMethod<[UserId], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[UserId, string], undefined>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'updateProfile' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];